
--DATABASE DICTIONARY
--ORACLE의 정보를 저장해놓은 TABLE 또는 VIEW

SELECT * FROM USER_CONSTRAINTS;

SELECT COUNT(*) FROM DICTIONARY;
SELECT * FROM DICTIONARY;

--종류
/*

USER_ 내꺼만 보는거, 현재계정의 정보 (가장작음)
ALL_  나한테 권한준 정보까지 보는거(중간)
DBA_  모든걸 다보는것, 권한준놈, 받은놈(가장큰거), 85%
V$  : ORACLE의 H/W정보

*/


SELECT * FROM USER_CONSTRAINTS;

SELECT * FROM ALL_CONSTRAINTS;

SELECT * FROM DBA_CONSTRAINTS;

SELECT * FROM V$VERSION;

SELECT * FROM USER_INDEXES;
SELECT * FROM USER_CATALOG;
SELECT * FROM USER_TABLES;
SELECT * FROM USER_VIEWS;
SELECT * FROM USER_TAB_PRIVS; --권한을 보여준다.
SELECT * FROM USER_SYS_PRIVS; --UNLIMITED 권한 확인됨

--VIEW
--SIMPLE VIEW


--SYS에서 먼저 CREATE권한을 주고 아래 실행

CREATE VIEW PER10_V
AS
SELECT * FROM PERSONNEL WHERE DNO=10;

SELECT * FROM PER10_V;  --확인

CREATE VIEW PER20_V
AS
SELECT PNO, PNAME, MANAGER, PAY, DNO FROM PERSONNEL;

SELECT * FROM PER20_V;



-- 평균 합계 구하는 뷰생성

CREATE VIEW PER_AVG
AS
SELECT DNO, AVG(PAY) 평균, SUM(PAY) 합계
FROM PERSONNEL
GROUP BY DNO;


SELECT * FROM PER_AVG; -- 이것만 쓰면 간단히 위의 명령가능
--뷰의 목적 : 보안, 코딩이 짧아진다.


--WHERE절이 가능
SELECT * FROM PER_AVG WHERE DNO=10;

SELECT * FROM PER_AVG WHERE 합계>7500;

--DML이 가능
SELECT * FROM PER20_V;

INSERT INTO PER20_V VALUES(1234,'JJJ','1001',2000,10);
SELECT * FROM PER20_V;

UPDATE PER20_V SET PNAME='AAA' WHERE PNO=1234

DELETE PER20_V WHERE PNO=1234;

SELECT * FROM PERSONNEL;

 --INSERT에러
 CREATE VIEW PER
 AS
 SELECT PNAME, JOB, PAY FROM PERSONNEL;

SELECT * FROM PER;

INSERT INTO PER VALUES ('BBB','ACCOUNT',3000);  --X

SELECT * FROM PER_AVG;

INSERT INTO PER VALUES('40', 1234, 5000); --X 뷰파일임  원본이 아님

--VIEW 수정
CREATE -> ALTER

--있으면 수정하고 없으면 만들어라
CREATE OR REPLACE VIEW PER20_V
(번호, 이름, 직업, 부서번호)
AS
SELECT PNO, PNAME, JOB, DNO FROM PERSONNEL
WHERE DNO=20;

SELECT * FROM PER20_V;

SELECT * FROM USER_VIEWS;

DROP VIEW PER_AVG;

--함수기반의 INDEX
SELECT * FROM PERSONNEL WHERE PNAME='SMITH';
SELECT * FROM PERSONNEL WHERE PNAME=UPPER('smith');








