--20141016

SELECT * FROM DBA_UNUSED_COL_TABS;

--테이블 주석확인
SELECT * FROM user_tab_comments;

--컬럼 주석확인
SELECT * FROM USER_COL_COMMENTS;

-- DCL
-- GRANT : 권한 부여
-- REVOKE : 권한 회수

--계정생성
CREATE USER TEST
IDENTIFIED BY TEST
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

--계정 추가 생성
CREATE USER GILDONG
IDENTIFIED BY 123
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

--계정목록을 본다.
SELECT USERNAME, PASSWORD, CREATED FROM DBA_USERS;

--V$는 동적딕션워리 , 일반적인 하드웨어적인정보 보여준다.
SELECT * FROM V$SESSION WHERE USERNAME IS NOT NULL;

--권한

--SYSTEM권한 : DB의 OBJECT를 생성(CREATE),수정(ALTER),삭제(DROP) 할수있는 권한(DBA->USERS)
--OBJECT권한 : OBJECT의 내용을 추가, 변경, 삭제, 검색 할수있는 권한(USER->USERS)
--OBJECT : TABLE, ROLE, SEQUENCE, VIEW, SYNONYM




--SYSTEM권한의 종료
SELECT * FROM SYSTEM_PRIVILEGE_MAP;

CREATE TABLE KIM.ABC
(ID NUMBER);


--권한주기
GRANT CREATE SESSION TO TEST;
--GRANT CREATE SESSION,CREATE TABLE TO TEST;

GRANT CREATE TABLE TO TEST;

GRANT CREATE SESSION, CREATE TABLE TO GILDONG;
REVOKE CREATE SESSION, CREATE TABLE FROM GILDONG;

-- ROLE
-- CONNECT : - CREATE SESSION 기능
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO GILDONG;


--ROLE

CREATE ROLE MANAGER;

SELECT * FROM DBA_ROLES

-- CREATE TABLE,CREATE USER 시스템권한
GRANT CREATE TABLE,CREATE USER TO MANAGER;

SELECT * FROM ROLE_SYS_PRIVS
WHERE ROLE = 'MANAGER';

SELECT * FROM ROLE_SYS_PRIVS
WHERE ROLE = 'CONNECT';

SELECT * FROM ROLE_SYS_PRIVS
WHERE ROLE = 'RESOURCE';

GRANT MANAGER TO GILDONG;

REVOKE MANAGER FROM GILDONG
REVOKE RESOURCE TABLE FROM GILDONG;

CREATE USER SUNSIN
IDENTIFIED BY 123
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

GRANT CONNECT, MANAGER TO SUNSIN;

CREATE USER SUN
IDENTIFIED BY 123
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

-------------------------------------------------------------

--SYS가 OBJ를 만든다.

CREATE ROLE OBJ;

GRANT OBJ TO SUNSIN;


--------------------------------------------------------------
--20141016

GRANT CREATE VIEW TO LEE  --LEE에게 CREATE 권한을준다.



SELECT COUNT(*) FROM DICTIONARY;
SELECT * FROM DICTIONARY;

GRANT CREATE VIEW TO KIM; --KIM에게 CREATE 권한을준다.


GRANT CREATE SYNONYM TO LEE;

-----------------


CREATE INDEX UPPER_IDX
ON KIM.PERSONNEL(LOWER(PNAME));  --대문자의 데이터를 소문자로 바꾸어 인덱스로 만들어라








